#include<iostream>
using namespace std;

int main(){
    int arr[4] = {12,24,35,46};

    cout << arr << endl;        // Give base address of array...
    cout << arr[0] << endl;
    cout << &arr << endl;       // Give base address of array...
    cout << &arr[0] << endl;    // Give base address of array...

    //But in case of pointers...
    int* p = arr;
    cout << p << endl;          // Give base address of array... 
    cout << &p << endl;         // Give address of pointer...

    return 0;
}